### ISSUE TITLE
Some pattern options that don't seem to work

### ISSUE THREAD

**Issue by instification** [collective/pat-tocify#2]
The following pattern options don't seem to be having any affect when set.
- [x] scrollTo
- [x] extendPage
- [x] highlightDefault

For all of these I have checked that the options are being properly read by the pattern.

**Comment by allcaps** [comment]
`scrollTo` is the offset of the _content_. In our demo the toc lives at ~75px from the top. Setting `"scrollTo": 75` will align the current heading with the top of the toc. The pink arrow indicates 'scrollTo':

<img width="688" alt="screen shot 2015-10-25 at 22 18 19" src="https://cloud.githubusercontent.com/assets/1969342/10717949/07bf29be-7b67-11e5-8a95-3e1c0001eec3.png">

The option name is a bit weird, but it 'works'.

`extendPage` happens, but due to float content the body collapses. I fixed it with a wrapper element and clearing floats: http://www.quirksmode.org/css/clearing.html

Don't know about highlightDefault... :/

**Comment by allcaps** [comment]
`highlightDefault` is set in the `_setActiveElement` function which is only called at window load. See https://github.com/gfranko/jquery.tocify.js/blob/master/src/javascripts/jquery.tocify.js#L179

Window load happens once and before jquery.tocify.js is initialised. :/

If I force a new load the highlight appears. But triggering a window.load isn't pretty. 

Just as a reference, afther https://github.com/collective/pat-tocify/blob/master/src/pat-tocify.js#L138 insert:

```
        var evt = document.createEvent('Event');
        evt.initEvent('load', false, false);
        window.dispatchEvent(evt);
```

**Comment by allcaps** [comment]
@instification: Can you have a look at 87c9040 ? I pushed direct to master but like a second pair of eyes on this ;).

**Comment by instification** [comment]
@allcaps it's perfect. I added a scrollTo of 75 to the demo page so that the headings are in line with the toc. Great work!
